### PR TITLE
Clearing the content of latch-based regfile at boot.

### PR DESCRIPTION
**Pull request by FrancescoConti**
This PR addresses issue #221 .

Adding a flip-flop generating a 1-cycle clear strobe when it samples
the first two clock edges after reset. In this way, the content of
the register-file is cleared in a similar way to what happens in the
FF-based register-file.

### CODE REVIEW

**Comment by davideschiavone** [comment]
Hi @FrancescoConti 

Thanks a lot for your PR.

Can you describe a little bit more why the RESET is not zeroing the latches?
Also, do you know the impact in area/performance that this extra "if elseif" that has been written to handle the clear signal from the flip-flop has on the core?

Thanks

**Comment by FrancescoConti** [comment]
The reset is not zeroing the latches, nor has it ever in SCMs :) about the reason: typically this is because we deployed SCM's as memory replacements (non-reset). Moreover, at least in the first standard cell library I could check, resettable latches are ~15% larger than the correspondent non-resettable ones. Also, I am unsure whether all libraries include resettable latches at all (maybe someone else can confirm / deny).

Rgd the area cost of this change: as far as I can count, the additional cost is 1 flip-flop, plus 33 OR2 gates being transformed in OR3 (for a 32-words register file).

**Comment by davideschiavone** [comment]
Ok I had misunderstand the issue - this looks like SW issue solved in HW. 
However as I wrote in the related issue, it looks anyway a convenient feature.
Forwarding this to OHW

**Comment by FrancescoConti** [comment]
The CI is doing something funny. Between a failing and a successful run I literally just removed a newline 🤣

**Comment by davideschiavone** [comment]
@FrancescoConti yes this happened to me as well....

**Pull request merged**
